name: CI / CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: CI - install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Quick check
        run: node -e "console.log('dependencies installed')"

  build-and-push:
    name: Build and push Docker image
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup QEMU and buildx so we can build multi-arch images
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            anant117/pyqhub-app:latest
            anant117/pyqhub-app:${{ github.sha }}

# Notes:
# - Create two repository secrets: DOCKERHUB_USERNAME and DOCKERHUB_TOKEN (a Docker Hub access token).
# - The workflow builds the app image using the repo Dockerfile and pushes two tags: :latest and :<git-sha>.
# - You can adjust platforms or tags as needed. If you do not need multi-arch, remove the `platforms` line.
